### PR TITLE
GitHub actions

### LINKED ISSUE #40: [enhancement] migrate from travis CI to github actions
Now github actions are a thing, we don't need to use travis anymore. -> migrate from travis CI to github actions

### PR DESCRIPTION
**Pull request by oukooveu**
Closes #40 

Test run: https://github.com/behavox/ansible-role-sonarqube/actions/runs/1415858575

### CODE REVIEW

**Review by lrk — CHANGES_REQUESTED** [review]
@oukooveu Hi, thank you for your contribution.

Just one thing to change: tests should be run on every PR too.

**Comment by oukooveu** [comment]
> @oukooveu Hi, thank you for your contribution.
> 
> Just one thing to change: tests should be run on every PR too.

It was done already and seems like this should be configured in settings (actions) because I've created test PR here: https://github.com/behavox/ansible-role-sonarqube/pull/1 and there are an appropriate checks for it.

**Comment by oukooveu** [comment]
@lrk and I'm not sure about `pull_request` condition, `on: push` is enough (checks are appear on pull request too), `on: pull_requests` only needed if we want to run checks on branch merged with target branch. But anyway, actions should be enabled in settings.

**Comment by lrk** [comment]
> @lrk and I'm not sure about `pull_request` condition, `on: push` is enough (checks are appear on pull request too), `on: pull_requests` only needed if we want to run checks on branch merged with target branch. But anyway, actions should be enabled in settings.

@oukooveu i was reading the documentation, your syntax is right.

**Review by lrk — APPROVED** [review]

**Pull request merged**
